name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.26.0, "v1.x"]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v4
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Test Deno Formatting
        run: deno fmt --check
      - name: Test Deno Linting
        run: deno lint
      - name: Test Deno Module
        run: deno test
      - name: Build npm module
        run: deno task build