name: Publish to Npm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ["v1.x"]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v4
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Test Deno Formatting
        run: deno fmt --check
      - name: Test Deno Linting
        run: deno lint
      - name: Test Deno Module
        run: deno test
      - name: Build npm module
        run: deno task build
      - name: Change directory to ./npm
        run: cd ./npm 
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}